services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/data

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8081:8081"
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf